name: FCM Technical Challenge
on: [push]
jobs:
 cypress-run: 
  runs-on: ubuntu-latest
  steps:
    -name: Checkout
     uses: actions/cache@v3.2.5
    -name:  Cypress.io
     uses: cypress-io/github-action@v5.0.9
     with: 
      start: npm start
